version: "3.8"
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ben
      POSTGRES_PASSWORD: llama
      POSTGRES_DB: llama
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
