"""testing

Revision ID: be713f0e92e0
Revises: 9e221588236c
Create Date: 2025-04-19 19:49:50.786382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be713f0e92e0'
down_revision: Union[str, None] = '9e221588236c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('uploads', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('uploads', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('uploads', sa.Column('tag', sa.String(length=50), nullable=True))
    op.drop_column('uploads', 'ocr_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('ocr_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('uploads', 'tag')
    op.drop_column('uploads', 'description')
    op.drop_column('uploads', 'title')
    op.drop_table('test')
    # ### end Alembic commands ###
